environment:
  OCTOBOT_DEFAULT_BRANCH: 0.4.0
  OCTOBOT_GH_REPO: https://github.com/Drakkar-Software/OctoBot.git
  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

cache:
  - '%LOCALAPPDATA%\pip\Cache'

install:
  - ps: |
      If ($env:APPVEYOR_REPO_TAG -eq "false") {
        $Env:TENTACLES_URL_TAG = "latest"
      }
  - ps: |
      try
      {
         git clone -q $env:OCTOBOT_GH_REPO -b $env:APPVEYOR_REPO_BRANCH
      }
      catch
      {
         git clone -q $env:OCTOBOT_GH_REPO -b $env:OCTOBOT_DEFAULT_BRANCH
      }
  - cd OctoBot
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install --prefer-binary -r requirements.txt -r dev_requirements.txt"
  - cd ..
  - mkdir new_tentacles
  - "xcopy Backtesting new_tentacles\\Backtesting /E/H/I"
  - "xcopy Evaluator new_tentacles\\Evaluator /E/H/I"
  - "xcopy Services new_tentacles\\Services /E/H/I"
  - "xcopy Trading new_tentacles\\Trading /E/H/I"
  - cd OctoBot
  - "%PYTHON%\\python.exe start.py tentacles -d ../new_tentacles -p ../new_tentacles.zip"
  - "%PYTHON%\\python.exe start.py tentacles --install --location ../new_tentacles.zip --all"

build: off

test_script:
  - "%PYTHON%\\python.exe -m pytest tentacles"

on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL
