trigger:
  branches:
    include:
    - master
    - 0.4.0
  tags:
    include:
    - '*'
  paths:
    include:
      - '*'

pr:
  autoCancel: true
  branches:
    include:
    - '*'

variables:
  OCTOBOT_GH_REPO: https://github.com/Drakkar-Software/OctoBot.git
  OCTOBOT_DEFAULT_BRANCH: 0.4.0

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
        Python38-64bit-full:
          PYTHON_VERSION: '3.8'
          PYTHON_ARCH: 'x64'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      addToPath: true
      architecture: $(PYTHON_ARCH)
  - powershell: |
      $env:BranchName = switch ($env:Build_Reason) {
        'PullRequest' { $env:System_PullRequest_SourceBranch.Replace('refs/pull/','').Replace('refs/heads/','') }
        default { $env:Build_SourceBranchName }
      }
      If ($env:SourceBranchLongName -notcontains "refs/tags/") {
        $env:TENTACLES_URL_TAG = "latest"
      }
      git clone -q $env:OCTOBOT_GH_REPO -b $env:BranchName
      if ($LastExitCode -ne 0) {
        git clone -q $env:OCTOBOT_GH_REPO -b $env:OCTOBOT_DEFAULT_BRANCH
      }
    displayName: 'Install OctoBot environment'
  - script: |
      cd OctoBot
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --prefer-binary -r requirements.txt -r dev_requirements.txt
    displayName: 'Install dependencies'
  - powershell: |
      mkdir new_tentacles
      xcopy Backtesting new_tentacles\\Backtesting /E/H/I
      xcopy Evaluator new_tentacles\\Evaluator /E/H/I
      xcopy Services new_tentacles\\Services /E/H/I
      xcopy Trading new_tentacles\\Trading /E/H/I
    displayName: 'Install OctoBot with Tentacles'
  - script: |
      cd OctoBot
      python start.py tentacles -d "../new_tentacles" -p "../new_tentacles.zip"
      python start.py tentacles --install --location "../new_tentacles.zip" --all
    displayName: 'Create OctoBot-Tentacles bundle'
  - script: |
      cd OctoBot
      python -m pytest --durations=0 tentacles
    displayName: 'Run OctoBot-Tentacles tests'

- job: macOS_Installed
  pool:
    vmImage: 'macOS-latest'
  strategy:
    maxParallel: 2
    matrix:
        Python38-64bit-full:
          PYTHON_VERSION: '3.8'
          PYTHON_ARCH: 'x64'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      addToPath: true
      architecture: $(PYTHON_ARCH)
  - script: |
      case "$BUILD_REASON" in
         "PullRequest")
            export HEAD_BRANCH_NAME=${SYSTEM_PULLREQUEST_SOURCEBRANCH//refs\/heads\//}
            export BRANCH_NAME=${HEAD_BRANCH_NAME//refs\/pull\//}
         ;;
         *) export BRANCH_NAME=$BUILD_SOURCEBRANCHNAME
         ;;
      esac
      git clone -q $OCTOBOT_GH_REPO -b $BRANCH_NAME || git clone -q $OCTOBOT_GH_REPO -b $OCTOBOT_DEFAULT_BRANCH
      cd OctoBot
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --prefer-binary -r requirements.txt -r dev_requirements.txt
    displayName: 'Install OctoBot'
  - script: |
      cd OctoBot
      python setup.py build_ext --inplace
      python setup.py install
    displayName: 'Compile and install OctoBot'
  - script: |
      mkdir new_tentacles
      cp -r Backtesting Evaluator Services Trading new_tentacles
      cd OctoBot
      python start.py tentacles -d "../new_tentacles" -p "../new_tentacles.zip"
      python start.py tentacles --install --location "../new_tentacles.zip" --all
    displayName: 'Create OctoBot-Tentacles bundle'
  - script: |
      cd OctoBot
      python -m pytest --durations=0 tentacles
    displayName: 'Run OctoBot-Tentacles tests'

- job: macOS_Python_sources
  pool:
    vmImage: 'macOS-latest'
  strategy:
    maxParallel: 2
    matrix:
        Python38-64bit-full:
          PYTHON_VERSION: '3.8'
          PYTHON_ARCH: 'x64'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
      addToPath: true
      architecture: $(PYTHON_ARCH)
  - script: |
      case "$BUILD_REASON" in
         "PullRequest")
            export HEAD_BRANCH_NAME=${SYSTEM_PULLREQUEST_SOURCEBRANCH//refs\/heads\//}
            export BRANCH_NAME=${HEAD_BRANCH_NAME//refs\/pull\//}
         ;;
         *) export BRANCH_NAME=$BUILD_SOURCEBRANCHNAME
         ;;
      esac
      git clone -q $OCTOBOT_GH_REPO -b $BRANCH_NAME || git clone -q $OCTOBOT_GH_REPO -b $OCTOBOT_DEFAULT_BRANCH
      cd OctoBot
      python -m pip install --upgrade pip setuptools wheel
      python -m pip install --prefer-binary -r requirements.txt -r dev_requirements.txt
    displayName: 'Install OctoBot'
  - script: |
      mkdir new_tentacles
      cp -r Backtesting Evaluator Services Trading new_tentacles
      cd OctoBot
      python start.py tentacles -d "../new_tentacles" -p "../new_tentacles.zip"
      python start.py tentacles --install --location "../new_tentacles.zip" --all
    displayName: 'Create OctoBot-Tentacles bundle'
  - script: |
      cd OctoBot
      python -m pytest --durations=0 tentacles
    displayName: 'Run OctoBot-Tentacles tests'
    continueOnError: true # Allow failure on python sources (memory check on staggered orders is failing). Waiting for fix
