name: OctoBot-Tentacles-Preview-Open
on:
  pull_request:
    types: [ opened ]

jobs:
  okteto_preview-open:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: okteto/login@master
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy preview environment
        uses: okteto/deploy-preview@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: pr-${{ github.event.number }}-tentacles-drakkarsoftware
          scope: personal
          timeout: 15m

      - name: Wait until tentacles are upload
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
          url: "https://octobot-pr-${{ github.event.number }}-tentacles-drakkarsoftware.cloud.okteto.net/"
          responseCode: '200'
          timeout: 180000 # 30min
          interval: 500

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'The preview environment is ready!'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

